Features Added:
Daniel-Ioannou/flutter_country_picker pull request #69
Opened 2022-02-24 17:12 UTC by sauravmankotia

- search by phoneCode
- search including "+"

2022-04-01 10:46 UTC, knowable-noujima-akinori commented
@Daniel-Ioannou i think this function should be include in the lib, please help to review on this PR

2022-04-01 10:47 UTC, uyit14 commented
@Daniel-Ioannou  Please look into this PR

2022-04-05 17:39 UTC, Daniel-Ioannou requested changes

2022-04-05 17:39 UTC, Daniel-Ioannou commented on lib/src/country.dart
> +  }
Please simplified. You wrote the "Search condition" twice. 
```suggestion
  bool startsWith(String query, CountryLocalizations? localizations) {
    String _query = query;
    if (query.startsWith("+")) {
      _query = query.replaceAll("+", "").trim();
    }

      return phoneCode.startsWith(_query.toLowerCase()) ||
          name.toLowerCase().startsWith(_query.toLowerCase()) ||
          countryCode.toLowerCase().startsWith(_query.toLowerCase()) ||
          (localizations
              ?.countryName(countryCode: countryCode)
              ?.toLowerCase()
              .startsWith(_query.toLowerCase()) ??
              false);
    }
```

2022-04-11 19:46 UTC, Daniel-Ioannou commented
Feature added at #78 and released in [v2.0.14](https://pub.dev/packages/country_picker/versions/2.0.14).

2022-04-11 19:46 UTC, closed without merging